mutation(
  $repoId: String!
  $base: String!
  $head: String!
  $title: String!
  $body: String!
) {
  createPullRequest(
    input: {
      repositoryId: $repoId
      baseRefName: $base
      headRefName: $head
      title: $title
    }
  ) {
    pullRequest {
      createdAt
    }
  }
}
