- name: "bug"
  color: "b71c1c"
  description: "Something isn't working"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "documentation"
  color: "673AB7"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "E0E0E0"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "1565C0"
  description: "New feature or request"

- name: "invalid"
  color: "424242"
  description: "This doesn't seem right or non-responses"

- name: "help wanted"
  color: "33691E"
  description: "Extra attention is needed"

- name: "question"
  color: "FFA000"
  description: "Further information is requested"

# Atutomated labels
- name: "patch"
  color: "FBC02D"
  description: "This pull request raises a PATCH version"

- name: BREAKING CHANGE
  color: D84315
  description: Introduces a breaking API change

- name: fix
  color: FFD54F
  description: A bug fix pull request

- name: chore
  color: A1887F
  description: Other changes that don't modify source code

- name: skip-changelog
  color: 4E342E
  description: Not to be included in changelog
