- name: "bug"
  color: "b71c1c"
  description: "Something isn't working"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "documentation"
  color: "673AB7"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "E0E0E0"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "1565C0"
  description: "New feature or request"

- name: "invalid"
  color: "424242"
  description: "This doesn't seem right or non-responses"

- name: "help wanted"
  color: "33691E"
  description: "Extra attention is needed"

- name: "question"
  color: "FFA000"
  description: "Further information is requested"

# Atutomated labels
- name: "major"
  color: "303F9F"
  description: "This pull request raises a MAJOR version"

- name: "minor"
  color: "00796B"
  description: "This pull request raises a MINOR version"

- name: "patch"
  color: "FBC02D"
  description: "This pull request raises a PATCH version"

- name: "automerge"
  color: "4DD0E1"
  description: "This pull request merges automatically"

- name: "autosquash"
  color: "9FA8DA"
  description: "This pull request squash automatically"
