name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "* $TITLE (#$NUMBER) @$AUTHOR"
template: |
  Update from $PREVIOUS_TAG

  ## Changes

  $CHANGES
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🧰 Maintenance
    label:
      - chore
      - docs
exclude-labels:
  - invalid
