name: Create Pull Request

on:
  create: {}

jobs:
  automated-pr:
    runs-on: ubuntu-20.04
    if: ${{ github.event.ref_type == 'branch' }}
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: current branch
        run: echo "BRANCH=`git name-rev --name-only HEAD`" >> $GITHUB_ENV

      - name: read template of pull request
        id: template
        run: |
          exec 1>> $GITHUB_ENV
          echo 'TEMPLATE<<EOF'
          cat .github/pull_request_template.md
          echo 'EOF'

      - name: create pull request
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

          COMMIT_SUBJECT=`git show --format=%s`

          gh pr create --draft \
            --base $PR_BASE \
            --title "WIP: $COMMIT_SUBJECT" \
            --body $PR_BODY
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PR_BASE: ${{ github.event.repository.default_branch }}
          PR_BODY: ${{ env.TEMPLATE }}
