name: Create Pull Request

on:
  push:
    branches-ignore:
      - "main"
      - "master"

env:
  WORKDIR: ${{ github.workspace }}

jobs:
  create-pr:
    runs-on: ubuntu-18.04
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: read graphql file
        id: gql
        run: |
          echo 'GQL_QUERY<<EOF' >> $GITHUB_ENV
          cat .github/create-pr.gql >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: read template of pull request
        id: template
        run: |
          echo 'TEMPLATE<<EOF' >> $GITHUB_ENV
          cat .github/pull_request_template.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: create pull request
        id: create_pr
        uses: octokit/graphql-action@7dfc23d9d9d2073901d250e142d36c0c19c5a88f
        with:
          query: |
            ${{ env.GQL_QUERY }}
          # variables
          repoId: ${{ github.event.repository.node_id }}
          baseRef: ${{ github.base_ref }}
          headRef: ${{ github.head_ref }}
          title: "[WIP] create by octokit/graphql-action."
          body: |
            ${{ env.TEMPLATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: response
        run: |
          echo 'created: ${{ steps.create_pr.outputs.data }}'
