name: debug

on:
  workflow_run:
    workflows:
      - Create Pull Request
    types:
      - completed

jobs:
  overwrite-event_json:
    runs-on: ubuntu-20.04
    steps:
      - name: id
        run: id

      - name: cannot overwrite about GITHUB_* env
        run: |
          echo "env: $GITHUB_EVENT_PATH"
        env:
          GITHUB_EVENT_PATH: "/home/runner/work/_temp/_github_workflow/hogehoge"

      - name: overwrite pull_request
        id: pr_info
        run: |
          OUTPUT="`dirname $GITHUB_EVENT_PATH`/tmp.json"
          PR_JSON=`cat $GITHUB_EVENT_PATH | jq '.workflow_run.pull_requests[] | select(.head.sha == "${{ github.event.workflow_run.head_sha }}") '`

          cat $GITHUB_EVENT_PATH |
            jq ".pull_request = $PR_JSON" > $OUTPUT

          mv $OUTPUT $GITHUB_EVENT_PATH

      - name: ls
        run: ls -al `dirname $GITHUB_EVENT_PATH`

      - name: jq
        run: cat $GITHUB_EVENT_PATH | jq '.'
