name: draft next release

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - closed

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: release drafter v5.12.1
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: release-drafter/release-drafter@3782ccd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
